import { useMemo, useState } from "react";
import {
  useReactTable,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
} from "@tanstack/react-table";
import type { ColumnDef } from "@tanstack/react-table";

import { DataTable } from "../../common/DataTable";
import TableSearch from "../../common/TableSearch";
import ColumnToggle from "../../common/ColumnToggle";
import Pagination from "../../common/Pagination";
import { ActionMenu } from "../../common/ActionMenu";

import NavigateButton from "../../common/NavigateButton";
import CustomPanel from "../../common/CustomPanel";

import { Plus } from "lucide-react";

type Report = {
  reportId: string;
  reportName: string;
  studyId: string;
  generatedBy: string;
  generatedDate: string;
  format: string;
  status: string;
};

const GenerateReport = () => {
  const data = useMemo<Report[]>(
    () => [
      {
        reportId: "REP001",
        reportName: "Study Summary Report",
        studyId: "ST001",
        generatedBy: "Admin",
        generatedDate: "20-05-2026",
        format: "PDF",
        status: "Generated",
      },
      {
        reportId: "REP002",
        reportName: "Subject Enrollment Report",
        studyId: "ST002",
        generatedBy: "Admin",
        generatedDate: "21-05-2026",
        format: "Excel",
        status: "Generated",
      },
      {
        reportId: "REP003",
        reportName: "Adverse Events Report",
        studyId: "ST003",
        generatedBy: "Coordinator",
        generatedDate: "22-05-2026",
        format: "PDF",
        status: "Pending",
      },
      {
        reportId: "REP004",
        reportName: "Adverse Events Report",
        studyId: "ST004",
        generatedBy: "Coordinator",
        generatedDate: "22-05-2026",
        format: "PDF",
        status: "Pending",
      },
      {
        reportId: "REP005",
        reportName: "Adverse Events Report",
        studyId: "ST005",
        generatedBy: "Coordinator",
        generatedDate: "22-05-2026",
        format: "PDF",
        status: "Pending",
      },
      {
        reportId: "REP006",
        reportName: "Adverse Events Report",
        studyId: "ST006",
        generatedBy: "Coordinator",
        generatedDate: "22-05-2026",
        format: "PDF",
        status: "Pending",
      },
      {
        reportId: "REP007",
        reportName: "Adverse Events Report",
        studyId: "ST007",
        generatedBy: "Coordinator",
        generatedDate: "22-05-2026",
        format: "PDF",
        status: "Pending",
      },
    ],
    []
  );

  const [globalFilter, setGlobalFilter] = useState("");
  const [columnVisibility, setColumnVisibility] = useState({});

  const [isPanelOpen, setIsPanelOpen] = useState(false);
  const [panelMode, setPanelMode] = useState<"view" | "edit">("view");

  const [_selectedRow, setSelectedRow] = useState<Report | null>(null);
  const [editRow, setEditRow] = useState<Report | null>(null);

  const columns: ColumnDef<Report>[] = useMemo(
    () => [
      { accessorKey: "reportId", header: "Report ID" },
      { accessorKey: "reportName", header: "Report Name" },
      { accessorKey: "studyId", header: "Study ID" },
      { accessorKey: "generatedBy", header: "Generated By" },
      { accessorKey: "generatedDate", header: "Generated Date" },
      { accessorKey: "format", header: "Format" },
      {
        accessorKey: "status",
        header: "Status",
        cell: ({ getValue }) => {
          const value = getValue<string>();
          return (
            <span
              className={`px-2 py-1 rounded text-xs font-medium ${
                value === "Generated"
                  ? "bg-green-100 text-green-700"
                  : "bg-yellow-100 text-yellow-700"
              }`}
            >
              {value}
            </span>
          );
        },
      },
      {
        id: "actions",
        header: "Actions",
        cell: ({ row }) => {
          const item = row.original;

          return (
            <ActionMenu
              item={item}
              onView={(data) => {
                setSelectedRow(data);
                setEditRow(data);
                setPanelMode("view");
                setIsPanelOpen(true);
              }}
              onEdit={(data) => {
                setSelectedRow(data);
                setEditRow(data);
                setPanelMode("edit");
                setIsPanelOpen(true);
              }}
              onAuditLog={(data) => console.log("Audit Log:", data)}
              onDelete={(data) => console.log("Delete:", data)}
            />
          );
        },
      },
    ],
    []
  );

  const table = useReactTable({
    data,
    columns,
    state: {
      globalFilter,
      columnVisibility,
    },
    onGlobalFilterChange: setGlobalFilter,
    onColumnVisibilityChange: setColumnVisibility,
    getCoreRowModel: getCoreRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
  });

  const handleSave = () => {
    if (panelMode === "view") {
      setIsPanelOpen(false);
      return;
    }

    console.log("Updated Report:", editRow);

    setSelectedRow(editRow);
    setIsPanelOpen(false);
  };

  return (
    <>
      {/* TABLE */}
      <div className="p-6">
        <div className="bg-white shadow-md rounded-lg p-6">
          <div className="flex justify-end items-center mb-4 gap-3">
            <TableSearch
              value={globalFilter}
              onChange={setGlobalFilter}
              placeholder="Search Reports..."
            />

            <ColumnToggle table={table} />

            <NavigateButton
              label="Add Report"
              path="/report-form"
              icon={<Plus size={18} />}
            />
          </div>

          <DataTable table={table} columns={columns} />

          <Pagination
            table={table}
            totalCount={table.getFilteredRowModel().rows.length}
          />
        </div>
      </div>

      {/* PANEL */}
      <CustomPanel
        isOpen={isPanelOpen}
        title={panelMode === "view" ? "View Report" : "Edit Report"}
        onClose={() => {
          setIsPanelOpen(false);
          setSelectedRow(null);
          setEditRow(null);
        }}
        onSave={handleSave}
        saveLabel={panelMode === "view" ? "Close" : "Update"}
      >
        {editRow && (
          <div className="space-y-4">
            {/* Report ID */}
            <div>
              <label className="block text-sm font-medium mb-1">
                Report ID
              </label>
              <input
                value={editRow.reportId}
                readOnly
                className="w-full border rounded-lg px-3 py-2 bg-gray-50"
              />
            </div>

            {/* Report Name */}
            <div>
              <label className="block text-sm font-medium mb-1">
                Report Name
              </label>
              <input
                value={editRow.reportName}
                readOnly={panelMode === "view"}
                onChange={(e) =>
                  setEditRow((prev) =>
                    prev ? { ...prev, reportName: e.target.value } : prev
                  )
                }
                className="w-full border rounded-lg px-3 py-2"
              />
            </div>

            {/* Study ID */}
            <div>
              <label className="block text-sm font-medium mb-1">
                Study ID
              </label>
              <input
                value={editRow.studyId}
                readOnly={panelMode === "view"}
                onChange={(e) =>
                  setEditRow((prev) =>
                    prev ? { ...prev, studyId: e.target.value } : prev
                  )
                }
                className="w-full border rounded-lg px-3 py-2"
              />
            </div>

            {/* Generated By */}
            <div>
              <label className="block text-sm font-medium mb-1">
                Generated By
              </label>
              <input
                value={editRow.generatedBy}
                readOnly={panelMode === "view"}
                onChange={(e) =>
                  setEditRow((prev) =>
                    prev ? { ...prev, generatedBy: e.target.value } : prev
                  )
                }
                className="w-full border rounded-lg px-3 py-2"
              />
            </div>

            {/* Format */}
            <div>
              <label className="block text-sm font-medium mb-1">
                Format
              </label>
              <select
                value={editRow.format}
                disabled={panelMode === "view"}
                onChange={(e) =>
                  setEditRow((prev) =>
                    prev ? { ...prev, format: e.target.value } : prev
                  )
                }
                className="w-full border rounded-lg px-3 py-2"
              >
                <option value="PDF">PDF</option>
                <option value="Excel">Excel</option>
              </select>
            </div>

            {/* Status */}
            <div>
              <label className="block text-sm font-medium mb-1">
                Status
              </label>
              <select
                value={editRow.status}
                disabled={panelMode === "view"}
                onChange={(e) =>
                  setEditRow((prev) =>
                    prev ? { ...prev, status: e.target.value } : prev
                  )
                }
                className="w-full border rounded-lg px-3 py-2"
              >
                <option value="Generated">Generated</option>
                <option value="Pending">Pending</option>
              </select>
            </div>
          </div>
        )}
      </CustomPanel>
    </>
  );
};

export default GenerateReport;