import { useMemo, useState } from "react";
import {
  useReactTable,
  getCoreRowModel,
  getFilteredRowModel,
  getPaginationRowModel,
} from "@tanstack/react-table";
import type { ColumnDef } from "@tanstack/react-table";

import { DataTable } from "../../common/DataTable";
import TableSearch from "../../common/TableSearch";
import ColumnToggle from "../../common/ColumnToggle";
import Pagination from "../../common/Pagination";
import { ActionMenu } from "../../common/ActionMenu";

type Report = {
  reportId: string;
  reportName: string;
  studyId: string;
  generatedBy: string;
  generatedDate: string;
  format: string;
  status: string;
};

const GenerateReport = () => {
  const data = useMemo<Report[]>(
    () => [
      {
        reportId: "REP001",
        reportName: "Study Summary Report",
        studyId: "ST001",
        generatedBy: "Admin",
        generatedDate: "20-05-2026",
        format: "PDF",
        status: "Generated",
      },
      {
        reportId: "REP002",
        reportName: "Subject Enrollment Report",
        studyId: "ST002",
        generatedBy: "Admin",
        generatedDate: "21-05-2026",
        format: "Excel",
        status: "Generated",
      },
      {
        reportId: "REP003",
        reportName: "Adverse Events Report",
        studyId: "ST003",
        generatedBy: "Coordinator",
        generatedDate: "22-05-2026",
        format: "PDF",
        status: "Pending",
      },
      {
        reportId: "REP004",
        reportName: "Visit Schedule Report",
        studyId: "ST004",
        generatedBy: "Admin",
        generatedDate: "23-05-2026",
        format: "Excel",
        status: "Generated",
      },
      {
        reportId: "REP005",
        reportName: "Laboratory Results Report",
        studyId: "ST005",
        generatedBy: "Researcher",
        generatedDate: "24-05-2026",
        format: "PDF",
        status: "Pending",
      },
    ],
    []
  );

  const [globalFilter, setGlobalFilter] = useState("");
  const [columnVisibility, setColumnVisibility] = useState({});

  const columns: ColumnDef<Report>[] = useMemo(
    () => [
      {
        accessorKey: "reportId",
        header: "Report ID",
      },
      {
        accessorKey: "reportName",
        header: "Report Name",
      },
      {
        accessorKey: "studyId",
        header: "Study ID",
      },
      {
        accessorKey: "generatedBy",
        header: "Generated By",
      },
      {
        accessorKey: "generatedDate",
        header: "Generated Date",
      },
      {
        accessorKey: "format",
        header: "Format",
      },
      {
        accessorKey: "status",
        header: "Status",
        cell: ({ getValue }) => {
          const value = getValue<string>();

          return (
            <span
              className={`px-2 py-1 rounded text-xs font-medium ${
                value === "Generated"
                  ? "bg-green-100 text-green-700"
                  : "bg-yellow-100 text-yellow-700"
              }`}
            >
              {value}
            </span>
          );
        },
      },
      {
        id: "actions",
        header: "Actions",
        cell: ({ row }) => {
          const item = row.original;

          return (
            <ActionMenu
              item={item}
              onView={(data) => console.log("View:", data)}
              onEdit={(data) => console.log("Edit:", data)}
               onAuditLog={(data) => console.log("Audit Log:", data)}
              onDelete={(data) => console.log("Delete:", data)}
            />
          );
        },
      },
    ],
    []
  );

  const table = useReactTable({
    data,
    columns,
    state: {
      globalFilter,
      columnVisibility,
    },
    onGlobalFilterChange: setGlobalFilter,
    onColumnVisibilityChange: setColumnVisibility,
    getCoreRowModel: getCoreRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
  });

  return (
    <div className="p-6">
      <div className="bg-white shadow-md rounded-lg p-6">
        {/* Header */}
        <div className="flex justify-end items-center mb-4 gap-3">
          <TableSearch
            value={globalFilter}
            onChange={setGlobalFilter}
            placeholder="Search Reports..."
          />

          <ColumnToggle table={table} />
        </div>

        {/* Table */}
        <DataTable table={table} columns={columns} />

        {/* Pagination */}
        <Pagination
          table={table}
          totalCount={table.getFilteredRowModel().rows.length}
        />
      </div>
    </div>
  );
};

export default GenerateReport;